spring.application.name=counterparty-service
server.port=${SERVER_PORT:8888}
logging.file.name=${LOGGING_FILE_NAME:/app/logs/counterparty-service.log}

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/counterparty_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:false}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.data-locations=${SPRING_SQL_INIT_DATA_LOCATIONS:classpath:data.sql}
spring.jpa.defer-datasource-initialization=${SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION:true}




