CREATE TABLE processing_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    stage VARCHAR(100) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_processing_history_trade_id_created_at ON processing_history (trade_id, created_at);
